name: flutter_tugas_fix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  unicons: ^2.1.0
  firebase_core: 2.3.0
  firebase_auth: 3.4.2
  google_sign_in: 5.4.2
  firebase_auth_web: 5.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

assets: 
  - assets/images/
  - assets/icons/

flutter: null
uses-material-design: true
